apiVersion: v1
kind: Service
metadata:
  name: backoffice-service
spec:
  selector:
    app: backoffice-pod
  ports:
  - port: 8084
    nodePort: 30884
    protocol: TCP
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-pod
  template:
    metadata:
      labels:
        app: backoffice-pod
    spec:
      containers:
      - name: backoffice-container
        image: pichayean/backoffice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: backoffice-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: backoffice.codingholiday.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: backoffice-service
           port:
             number: 80
